apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nuuqag6yo-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nuuqag6yo-python 
  name: nuuqag6yo-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nuuqag6yo-python 
