apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nuuqag6yo-python 
  janus-idp.io/tekton: nuuqag6yo-python
  backstage.io/kubernetes-id: nuuqag6yo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nuuqag6yo-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml